### ISSUE TITLE
Warning: ReactNative.createElement is deprecated. Use React.createElement from the "react" package instead

### ISSUE THREAD

**Issue by JakeLin** [JakeLin/ReactNativeWeather#8]
![screenshot_20160513-233651](https://cloud.githubusercontent.com/assets/573856/15249622/dc49d842-1963-11e6-864f-60ff4141fff0.png)

**Comment by philip13** [comment]
You should to **replace** the old method  **var React = require('react-native');**  to **import** just like this: 

```
import React, {  Component,} from 'react';
import {
  AppRegistry,
  Navigator,
  StyleSheet,
  ...
} from 'react-native';
```

**Comment by JakeLin** [comment]
thanks @philip13 it is a PR #12  for addressing this issue, please have a look if you have time, thanks.
